DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
WithOptimizations: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8

Environment: prod
Mqtt:
  Host: tcp://106.38.205.89:1883
  Open: true

MySQL:
  Host: localhost:3306
  UserName: root
  Password: ky123..com
  Name: order_system
Redis:
  Host: localhost:6379

Wechat:
  NotifyUrl: www.eeeat.com

