DisablePathCorrection: false
EnablePathEscape: false
FireMethodNotAllowed: true
DisableBodyConsumptionOnUnmarshal: true
WithOptimizations: true
TimeFormat: Mon, 01 Jan 2006 15:04:05 GMT
Charset: UTF-8

Environment: test
MqttHost: tcp://121.46.29.196:1883

MySQL:
  Host: localhost:3306
  UserName: root
  Password:
  Name: order_system
Redis:
  Host: localhost:6379

